/****************************************************************************** 
MCP4725 Example Waveform Sketch
Joel Bartlett
SparkFun Electronics
Sept. 11, 2014
https://github.com/sparkfun/MCP4725_Breakout

This sketch takes data from a lookup table to provide 
waveforms to be generated by the MCP4725 DAC. 

Development environment specifics:
Arduino 1.0+
Hardware Version V14

This code is beerware; if you see me (or any other SparkFun employee) at the local, 
and you've found our code helpful, please buy us a round!

Distributed as-is; no warranty is given. 

This code builds off the sketch written by Mark VandeWettering, which can be found here:
http://brainwagon.org/2011/02/24/arduino-mcp4725-breakout-board/
*/

#include <Wire.h>//Include the Wire library to talk I2C

//This is the I2C Address of the MCP4725, by default (A0 pulled to GND).
//Please note that this breakout is for the MCP4725A0. 
#define MCP4725_ADDR 0x60   
#define MCP4725_ADDR2 0x61   
//For devices with A0 pulled HIGH, use 0x61

//Sinewave Tables were generated using this calculator:
//http://www.daycounter.com/Calculators/Sine-Generator-Calculator.phtml


int lookup = 0;//varaible for navigating through the tables
int lookup2 = 257;

int sintab2[512]=
{
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
1366, 1366, 1366, 1366, 1366,1366,1366,1366,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0
};


void setup()
{
  Wire.begin();

  // Set A2 and A3 as Outputs to make them our GND and Vcc,
  //which will power the MCP4725
  pinMode(A2, OUTPUT);
  pinMode(A3, OUTPUT);

  digitalWrite(A2, LOW);//Set A2 as GND
  digitalWrite(A3, HIGH);//Set A3 as Vcc
}
//---------------------------------------------------
void loop()
{
  Wire.beginTransmission(MCP4725_ADDR);
  Wire.write(64);                     // cmd to update the DAC
  Wire.write(sintab2[lookup] >> 4);        // the 8 most significant bits...
  Wire.write((sintab2[lookup] & 15) << 4); // the 4 least significant bits...
  Wire.endTransmission();
  Wire.beginTransmission(MCP4725_ADDR2);
  Wire.write(64);                     // cmd to update the DAC
  Wire.write(sintab2[lookup2] >> 4);        // the 8 most significant bits...
  Wire.write((sintab2[lookup2] & 15) << 4); // the 4 least significant bits...
  Wire.endTransmission();
  lookup = (lookup + 1) & 511;
  lookup2 = (lookup2 + 1) & 511;
}
